In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("clean_crop_data.csv")
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
1995  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
1996   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
1997  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
1998  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
1999  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2000 rows x 8 columns]

In [3]:
df.shape

(2000, 8)

In [4]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['label'] = le.fit_transform(df['label'])


In [6]:
df.head()

N   P   K  temperature   humidity        ph    rainfall  label
0  90  42  43    20.879744  82.002744  6.502985  202.935536     18
1  85  58  41    21.770462  80.319644  7.038096  226.655537     18
2  60  55  44    23.004459  82.320763  7.840207  263.964248     18
3  74  35  40    26.491096  80.158363  6.980401  242.864034     18
4  78  42  42    20.130175  81.604873  7.628473  262.717340     18

In [7]:
df['label'].unique()

array([18,  9,  2,  7, 16, 11, 12,  1,  8, 17,  0, 10, 19, 13, 14, 15,  3,
        5,  6,  4])

### Model Train Test Split

In [9]:
# Input features
x = df.drop('label', axis=1)
# Target variable
y = df['label']  

In [10]:
x

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
1995  107  34  32    26.774637  66.413269  6.780064  177.774507
1996   99  15  27    27.417112  56.636362  6.086922  127.924610
1997  118  33  30    24.131797  67.225123  6.362608  173.322839
1998  117  32  34    26.272418  52.127394  6.758793  127.175293
1999  104  18  30    23.603016  60.396475  6.779833  140.937041

[2000 rows x 7 columns]

In [11]:
y

0       18
1       18
2       18
3       18
4       18
        ..
1995     4
1996     4
1997     4
1998     4
1999     4
Name: label, Length: 2000, dtype: int32

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=33)

In [13]:
x_train

N   P   K  temperature   humidity        ph    rainfall
1240  100  18  52    26.202345  80.382665  6.876067   56.479418
1608   31  30  29    26.585804  90.986176  5.558807  178.811608
719    20  62  18    29.363587  64.987429  7.366543   61.912087
739    49  72  15    31.558463  67.835638  7.137005   74.869608
1662   17  30  27    29.030650  90.790939  5.894027  205.572037
...   ...  ..  ..          ...        ...       ...         ...
658    37  49  25    29.914544  85.853844  6.415460   41.390815
578    15  45  23    24.204226  61.433787  7.224194   46.020396
1752  123  50  16    23.049205  75.538352  6.498052   70.656443
391    40  78  20    19.185728  20.833983  5.669236   80.152934
1044  109  91  53    29.667273  83.510142  6.010096  110.251110

[1400 rows x 7 columns]

In [14]:
x_test

N   P   K  temperature   humidity        ph    rainfall
766    34  66  19    32.970305  60.181221  7.586642   73.446787
182    60  57  24    18.661162  61.553272  6.121294   75.032477
1763  112  49  25    25.689595  77.906210  6.470135   66.194268
1814   67  43  38    25.216227  70.882596  7.299305  195.864555
596    22  51  16    27.965837  61.349001  8.639586   70.104721
...   ...  ..  ..          ...        ...       ...         ...
270    42  74  83    19.258256  14.280419  7.545258   65.780420
1839   90  48  45    24.064757  71.313429  6.509175  153.639021
51     76  60  39    20.045414  80.347756  6.766240  208.581016
219    31  70  77    20.888187  14.323138  6.492546   90.462283
443     1  76  17    28.434307  52.100108  6.012719  147.041482

[600 rows x 7 columns]

In [15]:
y_test

766      1
182      9
1763     5
1814     6
596     11
        ..
270      2
1839     6
51      18
219      2
443     16
Name: label, Length: 600, dtype: int32

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)


In [17]:
x_train_scaled

array([[ 1.27586732, -1.19427207,  1.13308283, ...,  0.43537941,
         0.47412653, -0.84028663],
       [-0.58017724, -0.65225703, -0.24595739, ...,  0.90584102,
        -1.18860295,  1.2790599 ],
       [-0.87606841,  0.79311641, -0.90549836, ..., -0.24768371,
         1.09323559, -0.74616825],
       ...,
       [ 1.89454885,  0.25110137, -1.02541491, ...,  0.22044464,
        -0.00302826, -0.59467648],
       [-0.33808447,  1.51580313, -0.78558182, ..., -2.20670477,
        -1.04921221, -0.43015432],
       [ 1.51796009,  2.10298609,  1.1930411 , ...,  0.57414079,
        -0.6189576 ,  0.09128215]])

In [18]:
x_test_scaled

array([[-0.49947965,  0.97378809, -0.84554009, ..., -0.46092786,
         1.37105909, -0.54633511],
       [ 0.19989946,  0.56727681, -0.54574874, ..., -0.40005201,
        -0.4785962 , -0.51886379],
       [ 1.59865768,  0.20593345, -0.48579047, ...,  0.3255029 ,
        -0.0382664 , -0.67198152],
       ...,
       [ 0.63028661,  0.70278057,  0.35362531, ...,  0.43383057,
         0.33549557,  1.79480062],
       [-0.58017724,  1.15445977,  2.63203959, ..., -2.49558105,
        -0.00997836, -0.25154979],
       [-1.38715314,  1.42546729, -0.96545663, ..., -0.81947449,
        -0.61564635,  0.72865771]])

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import xgboost as xb
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [20]:
# Logistic Regression Model
lrc = LogisticRegression(max_iter=300)
lrc

LogisticRegression(max_iter=300)

In [21]:
lrc.fit(x_train_scaled, y_train)

LogisticRegression(max_iter=300)

In [22]:
y_pred =lrc.predict(x_test)
y_pred

C:\Users\TANISHK\anaconda3\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([15, 18,  5, 18, 15, 18, 18, 15, 18, 15, 18, 15, 18, 18,  5, 18, 18,
       18, 18, 15, 18, 18, 18, 18, 18, 15, 18, 15, 18, 18, 15, 18, 15, 18,
       15,  5, 18, 15, 15,  5,  5,  5, 18, 18, 18, 18, 18, 18, 15, 18, 18,
       18, 18, 18, 18,  5, 18, 15, 15, 18, 18, 18, 15, 15, 18, 15, 18, 18,
       15, 15, 18, 15, 15, 15, 15, 18, 18, 18, 18, 18,  5, 18, 18, 18, 15,
       15,  5,  5, 18, 15, 18,  5, 18,  5, 15, 18, 18, 18, 18, 18, 15, 18,
       15, 18, 18, 15, 18, 18, 15, 18, 18, 18, 18,  5,  5, 15, 18, 18, 18,
       18, 15, 15, 18, 18, 18, 15,  5, 15, 15, 18,  5, 18, 18,  5, 15, 15,
       15, 18, 18,  5, 15, 18, 18, 18, 18, 18, 18, 18, 15, 18, 18,  5, 15,
       15, 18, 15, 18,  5, 18, 18, 15, 15,  5, 18, 15, 18, 15, 18, 18, 15,
       18,  5, 15, 18, 18, 15, 15, 15, 18, 18, 18, 18, 18, 15, 18, 18, 15,
       18, 15, 18, 15, 15, 18, 18,  5, 18, 18, 18,  5, 15, 15, 15, 15, 18,
       15, 18, 18, 15, 18,  5, 18, 15, 18, 18, 18, 15, 18, 18, 15, 15, 18,
       18, 18, 18, 18, 18

### Confusion Metric,Accuracy,Classification Report

In [24]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [25]:
accuracy_lrc = accuracy_score(y_test, y_pred)
print("Logistic Regression Accuracy:", accuracy_lrc)

Logistic Regression Accuracy: 0.10166666666666667


In [26]:
confusion_matrix_LR=confusion_matrix(y_test,y_pred)
print("Confusion Matrix - Logistic Regression",confusion_matrix_LR)

Confusion Matrix - Logistic Regression [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 39  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0 30  0  0  4  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 29  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 22  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 30  0]
 [ 0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0 12  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 33  0]
 [ 1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0 33  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 25  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0 32  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0  0 29  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 30  0  0  0  0]
 [ 0  0  0  0  0 26  0  0  0  0  0  0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 31  0]
 [ 0  0  0  0  0

In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        39
           1       0.00      0.00      0.00        35
           2       0.00      0.00      0.00        31
           3       0.00      0.00      0.00        22
           4       0.00      0.00      0.00        30
           5       0.32      0.65      0.43        34
           6       0.00      0.00      0.00        33
           7       0.00      0.00      0.00        37
           8       0.00      0.00      0.00        25
           9       0.00      0.00      0.00        33
          10       0.00      0.00      0.00        32
          11       0.00      0.00      0.00        30
          12       0.00      0.00      0.00        30
          13       0.00      0.00      0.00        28
          14       0.00      0.00      0.00        31
          15       0.06      0.39      0.11        28
          16       0.00      0.00      0.00        29
          17       0.00    

C:\Users\TANISHK\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\TANISHK\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\TANISHK\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


### SVM Model

In [29]:
# SVM Model
svm_model = SVC()
svm_model.fit(x_train_scaled, y_train)


SVC()

In [30]:
y_pred_svm = svm_model.predict(x_test_scaled)

In [31]:
y_pred_svm

array([ 1,  9,  5,  6, 11, 14,  4, 11,  7, 15,  4,  2,  7,  4, 13, 14,  3,
        3, 15,  8, 10,  4, 10, 14,  7, 12, 16,  1, 10, 16, 10, 18, 11, 14,
       11, 13, 10,  1,  2, 19, 19,  5, 16,  0, 10,  4,  3,  0, 11,  4,  6,
       10,  0,  0,  7, 13,  3,  8,  2, 18,  0, 15,  1,  8, 14,  1, 10, 15,
       12, 11,  9, 12,  7,  2,  8, 14, 14,  3, 16,  6,  5,  0, 16, 14,  1,
        8, 19,  5,  9, 11, 17, 19, 14,  5, 11, 18,  6,  1,  0,  9,  1, 10,
        2,  7,  7,  1,  5, 15,  8,  6, 14, 11,  0, 19, 13, 11, 14,  0,  6,
        0, 12,  2,  9,  2,  6, 11, 19, 12, 10,  9, 13,  6,  4, 19,  8, 15,
       15, 14, 10, 19,  8, 19, 16, 18,  6, 14, 16,  9, 19,  9, 14, 19, 19,
       11,  4, 13, 16,  5,  4,  4,  7, 15,  5,  4,  8,  7, 15,  3, 16,  2,
       16,  5, 12,  4,  4,  8, 12, 15,  9, 14,  0,  6, 16, 19,  9, 14,  1,
        6, 12, 10,  2,  1, 15,  9, 13,  7,  0,  6,  9,  2, 12,  2,  8,  6,
        1,  0,  6, 11, 10, 19, 17,  8,  7,  6,  9, 17,  9, 14,  2,  2,  5,
        7,  5,  9, 17,  3

In [32]:
print(classification_report(y_test, y_pred_svm))
print("SVM modelAccuracy :", accuracy_score(y_test, y_pred_svm))
cm_SVM = confusion_matrix(y_test, y_pred_svm)
print(cm_SVM)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        39
           1       0.97      0.97      0.97        35
           2       1.00      1.00      1.00        31
           3       1.00      1.00      1.00        22
           4       1.00      1.00      1.00        30
           5       1.00      1.00      1.00        34
           6       0.85      1.00      0.92        33
           7       0.97      1.00      0.99        37
           8       0.89      1.00      0.94        25
           9       1.00      1.00      1.00        33
          10       1.00      1.00      1.00        32
          11       1.00      0.93      0.97        30
          12       1.00      1.00      1.00        30
          13       1.00      1.00      1.00        28
          14       1.00      1.00      1.00        31
          15       1.00      1.00      1.00        28
          16       1.00      0.93      0.96        29
          17       1.00    

#### Decision Tree

In [34]:
dt_model = DecisionTreeClassifier(criterion="entropy")
dt_model.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [35]:
y_pred_dt = dt_model.predict(x_test)
y_pred_dt

array([ 1,  9,  5,  6, 11, 14,  4, 11,  7, 15,  4,  2,  7,  4, 13, 14,  3,
        3, 15,  8, 10,  4, 10, 14,  7, 12, 16,  1, 10, 16, 10, 18, 11, 14,
       11, 13, 10,  9,  2, 19, 19,  5, 16,  0, 10,  4,  3,  0, 11,  4,  6,
       10,  0,  0,  7, 13,  3,  8,  2,  6,  0, 15,  1,  8, 14,  1, 10, 15,
       12, 11,  9, 12,  7,  2,  8, 14, 14,  3, 16,  6,  5,  0, 16, 14,  1,
        8, 19,  5,  9, 11, 17, 19, 14,  5, 11, 18,  6,  1,  0,  9, 16, 10,
        2,  7,  7,  1,  5, 15,  8,  6, 14,  7,  0, 19, 13, 11, 14,  0,  6,
        0, 12,  2,  9,  2,  6, 11, 19, 12, 10,  9, 13,  6,  4, 19,  8, 15,
       15, 14, 10, 19, 11, 19, 16, 18,  6, 14, 16,  9, 19,  9, 14, 19, 19,
       11,  4, 13, 16,  5,  4,  4,  7, 15,  5,  4,  8,  7, 15,  3, 16,  2,
       16,  5, 12,  4,  4,  8, 12, 15,  9, 14,  0,  6, 16, 19,  9, 14,  1,
       18, 12, 10,  2,  1, 15,  4, 13,  7,  0,  6,  9,  2, 12,  2,  8,  6,
        1,  0,  6, 11, 10, 19, 17,  8,  7,  6,  9, 17, 11, 14,  2,  2,  5,
        7,  5,  9, 17,  3

In [36]:
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Accuracy:", accuracy_dt)


Decision Tree Accuracy: 0.9766666666666667


In [37]:
cm_DT = confusion_matrix(y_test, y_pred_dt)
print("Decision Tree Confusion matric:", cm_DT)


Decision Tree Confusion matric: [[39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 32  0  0  0  0  0  2  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 31  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 29  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 32  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 37  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0 29  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 32  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  0  0 29  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 30  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 31  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 

In [38]:
print("Classification Report for Decision Tree:\n")
print(classification_report(y_test, y_pred_dt))

Classification Report for Decision Tree:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        39
           1       1.00      0.91      0.96        35
           2       1.00      1.00      1.00        31
           3       1.00      1.00      1.00        22
           4       0.91      0.97      0.94        30
           5       1.00      1.00      1.00        34
           6       0.94      0.97      0.96        33
           7       0.93      1.00      0.96        37
           8       1.00      1.00      1.00        25
           9       0.94      0.88      0.91        33
          10       1.00      1.00      1.00        32
          11       0.97      0.97      0.97        30
          12       1.00      1.00      1.00        30
          13       0.93      1.00      0.97        28
          14       1.00      1.00      1.00        31
          15       1.00      1.00      1.00        28
          16       1.00      1.00      

### Random Forest

In [40]:
rf_model = RandomForestClassifier()
rf_model.fit(x_train, y_train)

RandomForestClassifier()

In [41]:
y_pred_rf = rf_model.predict(x_test)
y_pred_rf

array([ 1,  9,  5,  6, 11, 14,  4, 11,  7, 15,  4,  2,  7,  4, 13, 14,  3,
        3, 15,  8, 10,  4, 10, 14,  7, 12, 16,  1, 10, 16, 10, 18, 11, 14,
       11, 13, 10,  1,  2, 19, 19,  5, 16,  0, 10,  4,  3,  0, 11,  4,  6,
       10,  0,  0,  7, 13,  3,  8,  2, 18,  0, 15,  1,  8, 14,  1, 10, 15,
       12, 11,  9, 12,  7,  2,  8, 14, 14,  3, 16,  6,  5,  0, 16, 14,  1,
        8, 19,  5,  9, 11, 17, 19, 14,  5, 11, 18,  6,  9,  0,  9, 16, 10,
        2,  7,  7,  1,  5, 15,  8,  6, 14, 11,  0, 19, 13, 11, 14,  0,  6,
        0, 12,  2,  9,  2,  6, 11, 19, 12, 10,  9, 13,  6,  4, 19,  8, 15,
       15, 14, 10, 19, 11, 19, 16, 18, 18, 14, 16,  9, 19,  9, 14, 19, 19,
       11,  4, 13, 16,  5,  4,  4,  7, 15,  5,  4,  8,  7, 15,  3, 16,  2,
       16,  5, 12,  4,  4,  8, 12, 15,  9, 14,  0,  6, 16, 19,  9, 14,  1,
       18, 12, 10,  2,  1, 15,  9, 13,  7,  0,  6,  9,  2, 12,  2,  8,  6,
        1,  0,  6, 11, 10, 19, 17,  8,  7,  6,  9, 17,  9, 14,  2,  2,  5,
        7,  5,  9, 17,  3

In [42]:
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Accuracy:", accuracy_rf)
cm_RF = confusion_matrix(y_test, y_pred_rf)
print("Random Forest confusion matrix",cm_RF)

print("Classification Report for Random Forest:\n")
print(classification_report(y_test, y_pred_rf))

Random Forest Accuracy: 0.9966666666666667
Random Forest confusion matrix [[39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 31  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 33  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 37  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 33  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 32  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 30  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 

#### XGBoost

In [44]:
import xgboost as xb

In [45]:
xgb_model = xb.XGBClassifier()
xgb_model.fit(x_train, y_train)
# classifier3=xb.XGBClassifier()
# classifier3.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [46]:
y_pred_xb=xgb_model.predict(x_test)
print("confusion of XGBOOST",confusion_matrix(y_test,y_pred_xb))
print("accuray of XGBOOST",accuracy_score(y_test,y_pred_xb))
print("report of XGBOOST",classification_report(y_test,y_pred_xb))

confusion of XGBOOST [[39  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 35  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 31  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 34  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 33  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 37  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 25  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 33  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 32  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 30  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 30  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 28  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 31  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0

### All model accuracy comperision

In [48]:
# y_pred
# y_pred_svm
# y_pred_dt
# y_pred_rf
# y_pred_xb

model_accuracy = {
    "Logistic Regression": accuracy_score(y_test, y_pred),
    "SVM": accuracy_score(y_test, y_pred_svm),
    "Decision Tree": accuracy_score(y_test, y_pred_dt),
    "Random Forest": accuracy_score(y_test, y_pred_rf),
    "XGBoost": accuracy_score(y_test, y_pred_xb)
}

accuracy_df = pd.DataFrame(list(model_accuracy.items()), columns=["Model", "Accuracy"])
print(accuracy_df)

                 Model  Accuracy
0  Logistic Regression  0.101667
1                  SVM  0.981667
2        Decision Tree  0.976667
3        Random Forest  0.996667
4              XGBoost  0.996667


In [49]:
LR = accuracy_score(y_test, y_pred)
SVM=accuracy_score(y_test, y_pred_svm)
DT= accuracy_score(y_test, y_pred_dt)
RF= accuracy_score(y_test, y_pred_rf)
Xb=accuracy_score(y_test, y_pred_xb)

In [67]:
lst = ['LR','SVM','DT','RF','Xb']
best_model = lst[0]
for i in range(len(lst)-1):
    if lst[i] <= lst[i+1]:
        best_model = lst[i+1]
print(best_model)

Xb


In [69]:
print(best_model)

Xb


In [76]:
import pickle

file = open('crop_model_1.pkl', 'wb')
# dump information to that file
pickle.dump(best_model, file)

In [78]:
file

<_io.BufferedWriter name='crop_model_1.pkl'>